									/*----- TABLES -----*/
Drop table AOD_RECIPE_INGREDIENTS;             
Drop table AOD_RECIPE;      
Drop table AOD_USER_PROFILE;
Drop table AOD_INGREDIENT;
Drop table AOD_CUISINE;
Drop table AOD_CATEGORY;

Drop SEQUENCE  AOD_RECIPE_RECIPEID;
Drop SEQUENCE AOD_USERPROFILE_USERID;
Drop SEQUENCE AOD_CATEGORY_CATEGORYID;
Drop SEQUENCE AOD_CUISINE_CUISINEID;
Drop SEQUENCE AOD_INGREDIENT_NGREDIENTID;

/*drop index username_idx;
drop index emailuserid_idx;*/

                  
CREATE TABLE AOD_CATEGORY (
	CATEGORY_ID NUMBER(15) PRIMARY KEY,
	CATEGORY_NAME VARCHAR(30) NOT NULL
);

/*TESTED*/
CREATE TABLE AOD_CUISINE (
	CUISINE_ID NUMBER(15) PRIMARY KEY,
	CUISINE_NAME VARCHAR(20) NOT NULL
);

/*TESTED*/
CREATE TABLE AOD_INGREDIENT (
	INGREDIENT_ID NUMBER(15) PRIMARY KEY,
	INGREDIENT_NAME VARCHAR(20) NOT NULL
);

    /*TESTED*/
CREATE TABLE AOD_USER_PROFILE (
	USER_ID NUMBER(15) PRIMARY KEY,
	USER_NAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(10) NOT NULL,
	EMAIL NVARCHAR2(30) NOT NULL,
	CONSTRAINT password_restriction CHECK (
                                            (
										    LENGTH(password) > 6
											) 
                                    AND 
                                          (
                                           UPPER(SUBSTR(password, 1, 1)) = SUBSTR(password, 1, 1)/*First letter should be upper case*/
										   )
                                          ),
	CONSTRAINT email_restriction CHECK (EMAIL LIKE '%@%.%')					
);
              

/*TESTED*/
CREATE TABLE AOD_RECIPE (
	RECIPE_ID NUMBER(15) PRIMARY KEY,
	RECIPE_NAME NVARCHAR2(20) NOT NULL,
	USER_ID NUMBER(15) NOT NULL,
	CATEGORY_ID NUMBER(15) NOT NULL,
	COOKING_TIME VARCHAR2(20) NOT NULL,
	PORTION VARCHAR2(30) DEFAULT 1,
	CUISINE_ID NUMBER(15) NOT NULL,
	DESCRIPTION NVARCHAR2(255) NOT NULL,
	IS_PRIVATE NUMBER(1) DEFAULT 0,
	RECIPE_PHOTO_NAME NVARCHAR2(30),
	FOREIGN KEY (CATEGORY_ID) REFERENCES AOD_CATEGORY(CATEGORY_ID),
	FOREIGN KEY (USER_ID) REFERENCES AOD_USER_PROFILE(USER_ID),
	FOREIGN KEY (CUISINE_ID) REFERENCES AOD_CUISINE(CUISINE_ID),	
	CONSTRAINT ISPRIVATE_restriction CHECK (IS_PRIVATE = 0 OR IS_PRIVATE = 1)
)
ORGANIZATION INDEX;


/*TESTED*/

/*TESTED*/
CREATE TABLE AOD_RECIPE_INGREDIENTS (
  RECIPE_INGREDIENTS_ID NUMBER(15)  PRIMARY KEY,
  INGREDIENT_ID NUMBER(15),
  RECIPE_ID NUMBER(15), 
 
	FOREIGN KEY (RECIPE_INGREDIENTS_ID) REFERENCES AOD_INGREDIENT(INGREDIENT_ID)
);



								/*---- END OF TABLES -----*/



								/*----- SEQUENCES ------*/

/*SEQUENCE FOR RECIPEID IN AOD_RECIPE TABLE*/
/*TESTED*/
CREATE SEQUENCE AOD_RECIPE_RECIPEID 
START WITH 100000
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE
NOORDER;

/*SEQUENCE FOR USERID IN USERPROFILE TABLE*/
/*TESTED*/
CREATE SEQUENCE AOD_USERPROFILE_USERID
START WITH 300000
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE
NOORDER; 

/*SEQUENCE FOR CATEGORYID IN CATEGORY TABLE*/
/*TESTED*/
CREATE SEQUENCE AOD_CATEGORY_CATEGORYID
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE
NOORDER; 

/*SEQUENCE FOR CUISINEUD IN CUISINE TABLE*/
/*TESTED*/
CREATE SEQUENCE AOD_CUISINE_CUISINEID
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE
NOORDER; 

/*SEQUENCE FOR INGREDIENT_ID IN AOD_INGREDIENT TABLE*/
/*TESTED*/
CREATE SEQUENCE AOD_INGREDIENT_NGREDIENTID
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE
NOORDER;  

									/*END OF SEQUENCES*/
									
									
									/*INDEXES*/
									
/*I created IOT index with the AOD_RECIPE table - it will be really useful for search function*/

/*BITMAP INDEX ON USER_NAME*/
/*TESTED*/
CREATE BITMAP INDEX username_idx
ON AOD_USER_PROFILE(USER_NAME);

/*BITMAP INDEX ON CUISINE_NAME*/
/*TESTED*/
/*CREATE BITMAP INDEX cuisinename_idx
ON AOD_CUISINE(CUISINE_ID);*/

/*BITMAP INDEX ON CATEGORYNAME*/
/*TESTED*/
/*CREATE BITMAP INDEX categoryname_idx
ON AOD_CATEORY(CATEGORY_ID);*/

/*BITMAP INDEX ON CATEGORYNAME - MORE USEFUL, THAN BITMAP INDEX IN THIS CASE*/
CREATE UNIQUE INDEX emailuserid_idx
ON AOD_USER_PROFILE(USER_NAME, EMAIL);

								  /*END OF INDEXES*/