									/*----- TABLES -----*/

/*TESTED*/
CREATE TABLE AOD_RECIPE (
	RECIPEID NUMBER PRIMARY KEY,
	RECIPENAME NVARCHAR2(20) NOT NULL,
	USERID NUMBER NOT NULL,
	CATEGORYID NUMBER NOT NULL,
	COOKINGTIME VARCHAR(10) NOT NULL,
	PORTION NUMBER DEFAULT 1,
	CUISINEID NUMBER NOT NULL,
	DESCRIPTION NVARCHAR2(255) NOT NULL,
	ISPUBLIC CHAR(1) DEFAULT 'T',
	IMAGEID NUMBER NOT NULL,
	FOREIGN KEY (CATEGORYID) REFERENCES AOD_CATEGORY(CATEGORYID),
	FOREIGN KEY (USERID) REFERENCES AOD_USERPROFILE(USERID),
	FOREIGN KEY (CUISINEID) REFERENCES AOD_CUISINE(CUISINEID),
	FOREIGN KEY (IMAGEID) REFERENCES AOD_RECIPEIMAGE(IMAGEID),
	CONSTRAINT ispublic_restriction CHECK (ispublic = 'Tt' OR ispublic = 'Ff')
)
ORGANIZATION INDEX;

/*TESTED*/
CREATE TABLE AOD_USERPROFILE (
	USERID NUMBER PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	EMAIL NVARCHAR2(20) NOT NULL,
	CONSTRAINT password_restriction CHECK (
                                            (
										    LENGTH(password) > 10
											) 
                                    AND 
                                          (
                                           UPPER(SUBSTR(password, 1, 1)) = SUBSTR(password, 1, 1)
										   )
                                          ),
	CONSTRAINT email_restriction CHECK (EMAIL LIKE '%@%.%')					
);

/*TESTED*/
CREATE TABLE AOD_CATEGORY (
	CATEGORYID NUMBER PRIMARY KEY,
	CATEGORYNAME VARCHAR(20) NOT NULL,
	CATEGORYDESC VARCHAR(50) DEFAULT 'Food Category'
);

/*TESTED*/
CREATE TABLE AOD_CUISINE (
	CUISINEID NUMBER PRIMARY KEY,
	CUISINENAME VARCHAR(20),
	CUISINEDESC VARCHAR(50) DEFAULT 'Food Cuisine',
	DATEOFADDING DATE DEFAULT SYSDATE
);

/*TESTED*/
CREATE TABLE AOD_RECIPEIMAGE (
	IMAGEID NUMBER PRIMARY KEY,
	RECIPEID NUMBER NOT NULL,
	IMAGE BLOB 
);
ALTER TABLE AOD_RECIPEIMAGE ADD FOREIGN(RECIPEID) REFERENCES AOD_RECIPE(RECIPEID);

								/*---- END OF TABLES -----*/



								/*----- SEQUENCES ------*/

/*SEQUENCE FOR RECIPEID IN AOD_RECIPE TABLE*/
/*TESTED*/
CREATE SEQUENCE AOD_RECIPE_RECIPEID 
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE
NOORDER;

/*SEQUENCE FOR USERID IN USERPROFILE TABLE*/
/*TESTED*/
CREATE SEQUENCE AOD_USERPROFILE_USERID
START WITH 1000
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE
NOORDER; 

/*SEQUENCE FOR CATEGORYID IN CATEGORY TABLE*/
/*TESTED*/
CREATE SEQUENCE AOD_CATEGORY_CATEGORYID
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE
NOORDER; 

/*SEQUENCE FOR CUISINEUD IN CUISINE TABLE*/
/*TESTED*/
CREATE SEQUENCE AOD_CUISINE_CUISINEID
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE
NOORDER; 

/*SEQUENCE FOR IMAGEID IN IMAGE TABLE*/
/*TESTED*/
CREATE SEQUENCE AOD_IMAGE_IMAGEID
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCACHE
NOORDER;  

									/*END OF SEQUENCES*/
									
									
									/*INDEXES*/
									
/*I created IOT index with the AOD_RECIPE table - it will be really useful for search function*/

/*BITMAP INDEX ON USERNAME*/
/*TESTED*/
CREATE BITMAP INDEX username_idx
ON AOD_USERPROFILE(USERNAME);

/*BITMAP INDEX ON CUISINENAME*/
/*TESTED*/
CREATE BITMAP INDEX cuisinename_idx
ON AOD_CUISINE(CUISINENAME);

/*BITMAP INDEX ON CATEGORYNAME*/
/*TESTED*/
CREATE BITMAP INDEX categoryname_idx
ON AOD_CATEORY(CATEGORYNAME);

/*BITMAP INDEX ON CATEGORYNAME - MORE USEFUL, THAN BITMAP INDEX IN THIS CASE*/
CREATE UNIQUE INDEX emailuserid_idx
ON AOD_USERPROFILE(USERNAME, EMAIL);

								  /*END OF INDEXES*/
								  