CREATE OR REPLACE FUNCTION TEST_USER_INPUT
(
	usern IN AOD_USER_PROFILE.USER_NAME%TYPE,
	passw IN AOD_USER_PROFILE.PASSWORD%TYPE,
)
RETURN NUMBER 
IS
d_test NUMBER(1) := 0;
BEGIN
 DECLARE 
 usid AOD_USER_PROFILE.USER_ID%TYPE;
 BEGIN
	SELECT USER_ID
	INTO usid
	FROM AOD_USER_PROFILE
	WHERE USER_NAME = usern;
	IF SQL%NOTFOUND THEN
	    d_test := 1
	END IF;
	usid := null;
	SELECT USER_ID
	INTO usid
	FROM AOD_USER_PROFILE
	WHERE USER_NAME = usern AND PASSWORD = passw;
	IF SQL%NOTFOUND THEN
		d_test := 2
	END IF;
 END;
 RETURN d_test;
END TEST_USER_INPUT;